// build.rs — generate `chimera_ffi.h` for Swift's bridging header.
//
// The header lands at:
//   crates/chimera-ffi/include/chimera_ffi.h
//
// Swift's bridging-header references this path; Xcode adds the directory
// to its HEADER_SEARCH_PATHS via the project file (or SPM Package.swift).

use std::env;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=cbindgen.toml");

    let crate_dir = env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR not set");
    let out_dir = PathBuf::from(&crate_dir).join("include");
    std::fs::create_dir_all(&out_dir).ok();

    let header = out_dir.join("chimera_ffi.h");

    // Best-effort: if cbindgen isn't available (e.g. on a no-network build),
    // skip header generation. The pre-committed header in `include/` is the
    // source of truth.
    let cfg = cbindgen::Config {
        language:        cbindgen::Language::C,
        cpp_compat:      true,
        header:          Some("// Generated by cbindgen. DO NOT EDIT.\n\
                               // Run `cargo build -p chimera-ffi` to regenerate.".into()),
        pragma_once:     true,
        include_guard:   Some("CHIMERA_FFI_H".into()),
        documentation:   true,
        ..Default::default()
    };

    match cbindgen::Builder::new()
        .with_config(cfg)
        .with_crate(&crate_dir)
        .generate()
    {
        Ok(bindings) => {
            bindings.write_to_file(&header);
            println!("cargo:warning=chimera-ffi: wrote header to {}", header.display());
        }
        Err(e) => {
            println!("cargo:warning=cbindgen skipped: {} (using checked-in header)", e);
        }
    }
}
