// Generated by cbindgen. DO NOT EDIT.
// Run `cargo build -p chimera-ffi` to regenerate.

#ifndef CHIMERA_FFI_H
#define CHIMERA_FFI_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Initialise the engine. Idempotent — safe to call multiple times.
 * Returns 0 on success, negative on failure.
 */
int chimera_init(void);

/**
 * Return the engine version string. Caller must `chimera_string_free`.
 */
char *chimera_version(void);

/**
 * Free a string previously returned by any FFI function.
 *
 * # Safety
 * `ptr` must be either null or a value previously returned by a
 * `chimera_*` function that returns `*mut c_char`. Passing any other
 * pointer is undefined behaviour.
 */
void chimera_string_free(char *ptr);

/**
 * Send a JSON request to the engine, receive a JSON response.
 *
 * This is the single dispatch entry-point Swift uses. The Swift bridge
 * serialises a `Request`, calls `chimera_dispatch`, parses the returned
 * JSON into a `Response`.
 *
 * # Safety
 * `request` must be a valid NUL-terminated UTF-8 JSON string.
 * The returned pointer must be freed with `chimera_string_free`.
 */
char *chimera_dispatch(const char *request);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CHIMERA_FFI_H */
